show_print : false

mode: 
  online : true
  filter : 2 # 0: no filter 1:gh_filter 2:ukf_filter
  imu : true
camera:
  resolution_x : 1280
  resolution_y : 720
  frame_rate : 30
imu:
  bps: 921600
  port: '/dev/ttyUSB0'
  timeout: 20
  show_print : false
needle_marker:
  shape : 5 # 0:do not detect 4:DICT_4X4_50 5:DICT_5X5_50
  side_length : 0.004
  
ref_marker:
  shape : 0 # 0:do not detect 4:DICT_4X4_50 5:DICT_5X5_50
  side_length : 0.008
gh_filter:
  g : 0.5
  h : 0.5
  data_shape : 7
  max_unmeansure_frames : 30
  dt : 1
ukf_filter:
  marker:
    q_shape : 4
    xyz_shape : 3
    v_xyz_shape : 3
    accu_q_shape : 4
    acc_xyz_shape : 3
    queue_size : 100
needle:
  length : 0.012185
  depth_to_needle : 0.001082
  radius : 0.000101


